/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcomputer_ComputerJNI */

#ifndef _Included_jcomputer_ComputerJNI
#define _Included_jcomputer_ComputerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcomputer_ComputerJNI
 * Method:    computerMove
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jcomputer_ComputerJNI_computerMove
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
